# Generated by Django 5.1.1 on 2024-11-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="site/logo")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=4)),
                ("user_name", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        default="users/avatars/default.jpg",
                        upload_to="users/avatars/%Y%m%d/",
                    ),
                ),
            ],
        ),
    ]
